#!/usr/bin/env python3
"""Generate deterministic memory index artifacts from source memory records."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from memory_utils import (
    REQUIRED_FIELDS,
    ensure_safe_content_path,
    load_registry,
    parse_front_matter,
    repo_root,
    validate_metadata,
)


class MemoryIndexError(ValueError):
    pass


def discover_memory_files(root: Path):
    memory_root = root / "memory"
    paths = []
    for path in memory_root.rglob("*.md"):
        if path.name.lower() == "readme.md":
            continue
        paths.append(path)
    return sorted(paths, key=lambda item: item.relative_to(root).as_posix())


def build_index(root: Path):
    errors = []
    records = []
    ids = {}

    for path in discover_memory_files(root):
        rel = path.relative_to(root).as_posix()
        try:
            metadata, body = parse_front_matter(path)
        except Exception as exc:  # noqa: BLE001
            errors.append(f"{rel}: {exc}")
            continue

        meta_errors = validate_metadata(metadata)
        if meta_errors:
            errors.append(f"{rel}: " + "; ".join(meta_errors))
            continue

        content_path = ensure_safe_content_path(str(metadata["contentPath"]))
        if content_path != rel:
            errors.append(f"{rel}: contentPath mismatch ({content_path})")

        if metadata["id"] in ids:
            errors.append(f"duplicate memory id {metadata['id']}: {ids[metadata['id']]} and {rel}")
        ids[metadata["id"]] = rel

        excerpt = ""
        for line in body.splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            excerpt = stripped[:180]
            break

        record = {field: metadata[field] for field in REQUIRED_FIELDS}
        record["path"] = rel
        record["excerpt"] = excerpt
        records.append(record)

    records.sort(key=lambda item: item["id"])
    record_ids = {row["id"] for row in records}

    try:
        registry = load_registry(root)
    except Exception as exc:  # noqa: BLE001
        errors.append(f"memory/registry.json: {exc}")
        registry = {"records": []}

    registry_ids = set()
    for row in registry.get("records", []):
        row_id = row.get("id")
        if row_id in registry_ids:
            errors.append(f"memory/registry.json: duplicate id {row_id}")
        registry_ids.add(row_id)
        if row_id not in record_ids:
            errors.append(f"memory/registry.json: id missing source file: {row_id}")
        if row.get("path"):
            p = root / row["path"]
            if not p.is_file():
                errors.append(f"memory/registry.json: path missing: {row['path']}")

    for record in records:
        if record["id"] not in registry_ids:
            errors.append(f"source record missing from memory/registry.json: {record['id']}")
        for related in record.get("related", []):
            if related not in record_ids:
                errors.append(f"{record['path']}: related id not found: {related}")

    if errors:
        raise MemoryIndexError("\n".join(sorted(errors)))

    return {
        "schemaVersion": "1.0.0",
        "recordCount": len(records),
        "records": records,
    }


def render_json(index) -> str:
    return json.dumps(index, indent=2, ensure_ascii=False) + "\n"


def render_markdown(index) -> str:
    lines = [
        "# Generated Memory Index",
        "",
        "> Generated from source memory records. Do not edit this file directly.",
        "",
        "| ID | Title | Type | Scope | Status | Path | Tags |",
        "|---|---|---|---|---|---|---|",
    ]
    for item in index["records"]:
        tags = ", ".join(item.get("tags", []))
        lines.append(
            "| {id} | {title} | {type} | {scope} | {status} | {path} | {tags} |".format(
                id=item["id"],
                title=item["title"],
                type=item["type"],
                scope=item["scope"],
                status=item["status"],
                path=item["path"],
                tags=tags,
            )
        )
    lines.extend(["", f"Total: {index['recordCount']} memory records.", ""])
    return "\n".join(lines)


def write_or_check(outputs, check=False):
    stale = []
    for path, content in outputs.items():
        if check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        values = []
        for path in stale:
            try:
                values.append(str(path.relative_to(repo_root())))
            except ValueError:
                values.append(str(path))
        display = ", ".join(values)
        raise MemoryIndexError("stale generated files: " + display)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated memory index files are stale")
    args = parser.parse_args(argv)

    root = repo_root()
    try:
        index = build_index(root)
        outputs = {
            root / "generated" / "memory-index.json": render_json(index),
            root / "generated" / "memory-index.md": render_markdown(index),
        }
        write_or_check(outputs, check=args.check)
    except MemoryIndexError as exc:
        print(f"FAIL {exc}", file=sys.stderr)
        return 1

    state = "is current" if args.check else "generated"
    print(f"PASS memory index {state} ({index['recordCount']} records)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
