#!/usr/bin/env python3
"""Generate deterministic skill registry artifacts from SKILL.md front matter."""
import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REQUIRED = ("id", "name", "version", "description", "triggers", "inputs", "outputs", "dependencies", "status")
LIST_FIELDS = {"triggers", "inputs", "outputs", "dependencies"}


class RegistryError(ValueError):
    pass


def parse_scalar(value):
    value = value.strip().strip('"').strip("'")
    if value in ("[]", ""):
        return [] if value == "[]" else ""
    if value in ("null", "~"):
        return None
    return value


def parse_front_matter(path):
    text = path.read_text(encoding="utf-8-sig").replace("\r\n", "\n")
    if not text.startswith("---\n") or "\n---\n" not in text:
        raise RegistryError(f"{path}: missing YAML front matter")
    lines = text.split("\n---\n", 1)[0].splitlines()[1:]
    result = {}
    current = None
    for number, line in enumerate(lines, 2):
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if line.startswith((" ", "\t")):
            stripped = line.strip()
            if current in LIST_FIELDS and stripped.startswith("- "):
                result[current].append(parse_scalar(stripped[2:]))
                continue
            if current not in LIST_FIELDS:
                continue
            raise RegistryError(f"{path}:{number}: unsupported YAML syntax")
        if ":" not in line:
            raise RegistryError(f"{path}:{number}: expected key: value")
        key, raw = line.split(":", 1)
        current = key.strip()
        result[current] = [] if current in LIST_FIELDS and not raw.strip() else parse_scalar(raw)
    return result


def discover_skills(root=ROOT):
    return sorted(root.glob(".agent/skills/**/SKILL.md"), key=lambda p: p.relative_to(root).as_posix())


def build_registry(root=ROOT):
    skills = []
    errors = []
    ids = {}
    for path in discover_skills(root):
        rel = path.relative_to(root).as_posix()
        try:
            metadata = parse_front_matter(path)
        except (OSError, UnicodeError, RegistryError) as exc:
            errors.append(str(exc))
            continue
        missing = [field for field in REQUIRED if field not in metadata or metadata[field] in (None, "")]
        if missing:
            errors.append(f"{rel}: missing required metadata: {', '.join(missing)}")
            continue
        if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", str(metadata["id"])):
            errors.append(f"{rel}: invalid skill id: {metadata['id']}")
        if not re.fullmatch(r"\d+\.\d+\.\d+", str(metadata["version"])):
            errors.append(f"{rel}: invalid semantic version: {metadata['version']}")
        for field in LIST_FIELDS:
            if not isinstance(metadata.get(field), list):
                errors.append(f"{rel}: {field} must be a YAML list")
        skill_id = str(metadata["id"])
        if skill_id in ids:
            errors.append(f"duplicate skill id {skill_id}: {ids[skill_id]} and {rel}")
        ids[skill_id] = rel
        skill = {field: metadata.get(field) for field in REQUIRED}
        skill["path"] = rel
        skill["replaces"] = metadata.get("replaces")
        skill["deprecatedBy"] = metadata.get("deprecatedBy")
        skills.append(skill)
    known = {skill["id"] for skill in skills}
    for skill in skills:
        for dependency in skill.get("dependencies", []):
            if dependency not in known:
                errors.append(f"{skill['path']}: unknown dependency: {dependency}")
    if errors:
        raise RegistryError("\n".join(sorted(errors)))
    skills.sort(key=lambda item: (item["id"], item["path"]))
    return {"schemaVersion": "1.0.0", "skills": skills}


def render_json(registry):
    return json.dumps(registry, indent=2, ensure_ascii=False) + "\n"


def render_markdown(registry):
    lines = [
        "# Generated Skill Registry", "",
        "> Generated from `SKILL.md` front matter. Do not edit this file directly.", "",
        "| ID | Name | Version | Status | Path | Dependencies |", "|---|---|---|---|---|---|",
    ]
    for skill in registry["skills"]:
        deps = ", ".join(f"`{item}`" for item in skill["dependencies"]) or "None"
        lines.append(f"| `{skill['id']}` | {skill['name']} | {skill['version']} | {skill['status']} | `{skill['path']}` | {deps} |")
    lines.extend(["", f"Total: {len(registry['skills'])} skills.", ""])
    return "\n".join(lines)


def write_or_check(outputs, check=False):
    stale = []
    for path, content in outputs.items():
        if check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        def display(path):
            try:
                return str(path.relative_to(ROOT))
            except ValueError:
                return str(path)
        raise RegistryError("stale generated files: " + ", ".join(display(path) for path in stale))


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated registry files are stale")
    args = parser.parse_args(argv)
    try:
        registry = build_registry(ROOT)
        outputs = {ROOT / "generated/skills.json": render_json(registry), ROOT / "generated/skills.md": render_markdown(registry)}
        write_or_check(outputs, args.check)
    except RegistryError as exc:
        print(f"FAIL {exc}", file=sys.stderr)
        return 1
    print(f"PASS skill registry {'is current' if args.check else 'generated'} ({len(registry['skills'])} skills)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
