#!/usr/bin/env python3
"""Generate deterministic profile index artifacts from source profile records.

Mirrors scripts/generate-memory-index.py's shape and conventions. profile/
is not added to scripts/index-repository.py's CATEGORIES -- this dedicated
indexer is the only path, matching the existing memory/ precedent (Task 005,
resolves the requirements.md Open Question on repository-index category).

The index is a summary view (id, path, role, team, active) -- deliberately
smaller than the full profile record, so it is safe to expose more broadly
than raw profile/ content. An empty profile/ (no profile authored yet) is a
valid, expected state and produces an empty, valid index.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from memory_utils import parse_front_matter, repo_root  # noqa: E402
from profile import SCHEMA_VERSION  # noqa: E402
from profile import registry as profile_registry  # noqa: E402
from profile.validate import validate_profile_record, validate_registry_shape  # noqa: E402


class ProfileIndexError(ValueError):
    pass


def discover_profile_files(root: Path) -> list[Path]:
    profile_root = root / "profile"
    if not profile_root.is_dir():
        return []
    paths = []
    for path in profile_root.glob("*.md"):
        if path.name.lower() == "readme.md":
            continue
        paths.append(path)
    return sorted(paths, key=lambda item: item.relative_to(root).as_posix())


def build_index(root: Path) -> dict:
    errors: list[str] = []
    records: list[dict] = []
    ids: dict[str, str] = {}

    for path in discover_profile_files(root):
        rel = path.relative_to(root).as_posix()
        try:
            metadata, _body = parse_front_matter(path)
        except Exception as exc:  # noqa: BLE001
            errors.append(f"{rel}: {exc}")
            continue

        failures, _warnings = validate_profile_record(metadata)
        if failures:
            errors.append(f"{rel}: " + "; ".join(failures))
            continue

        profile_id = metadata["id"]
        if profile_id in ids:
            errors.append(f"duplicate profile id {profile_id}: {ids[profile_id]} and {rel}")
        ids[profile_id] = rel

        records.append(
            {
                "id": profile_id,
                "path": rel,
                "role": metadata["role"],
                "team": metadata["team"],
                # active is resolved from the registry below, once loaded,
                # so a single file cannot misreport itself as active.
                "active": False,
            }
        )

    records.sort(key=lambda item: item["id"])
    record_ids = {row["id"] for row in records}

    try:
        registry = profile_registry.load_registry(root)
    except Exception as exc:  # noqa: BLE001
        errors.append(f"profile/registry.json: {exc}")
        registry = {"schemaVersion": SCHEMA_VERSION, "profiles": []}

    reg_failures, _reg_warnings = validate_registry_shape(registry)
    errors.extend(f"profile/registry.json: {msg}" for msg in reg_failures)

    active_ids: set[str] = set()
    registry_ids: set[str] = set()
    for entry in registry.get("profiles", []):
        entry_id = entry.get("id")
        if entry_id in registry_ids:
            errors.append(f"profile/registry.json: duplicate id {entry_id}")
        registry_ids.add(entry_id)
        if entry_id not in record_ids:
            errors.append(f"profile/registry.json: id missing source file: {entry_id}")
        entry_path = entry.get("path")
        if entry_path and not (root / entry_path).is_file():
            errors.append(f"profile/registry.json: path missing: {entry_path}")
        if entry.get("active") is True:
            active_ids.add(entry_id)

    for record in records:
        if record["id"] not in registry_ids:
            errors.append(f"source record missing from profile/registry.json: {record['id']}")
        if record["id"] in active_ids:
            record["active"] = True

    if errors:
        raise ProfileIndexError("\n".join(sorted(errors)))

    return {
        "schemaVersion": SCHEMA_VERSION,
        "recordCount": len(records),
        "records": records,
    }


def render_json(index: dict) -> str:
    return json.dumps(index, indent=2, ensure_ascii=False) + "\n"


def render_markdown(index: dict) -> str:
    lines = [
        "# Generated Profile Index",
        "",
        "> Generated from source profile records. Do not edit this file directly.",
        "",
        "| ID | Role | Team | Active | Path |",
        "|---|---|---|---|---|",
    ]
    for item in index["records"]:
        lines.append(
            "| {id} | {role} | {team} | {active} | {path} |".format(
                id=item["id"],
                role=item["role"],
                team=item["team"],
                active=str(item["active"]).lower(),
                path=item["path"],
            )
        )
    lines.extend(["", f"Total: {index['recordCount']} profile record(s).", ""])
    return "\n".join(lines)


def write_or_check(outputs: dict, check: bool = False) -> None:
    stale = []
    for path, content in outputs.items():
        if check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        values = []
        for path in stale:
            try:
                values.append(str(path.relative_to(repo_root())))
            except ValueError:
                values.append(str(path))
        raise ProfileIndexError("stale generated files: " + ", ".join(values))


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated profile index files are stale")
    args = parser.parse_args(argv)

    root = repo_root()
    try:
        index = build_index(root)
        outputs = {
            root / "generated" / "profile-index.json": render_json(index),
            root / "generated" / "profile-index.md": render_markdown(index),
        }
        write_or_check(outputs, check=args.check)
    except ProfileIndexError as exc:
        print(f"FAIL {exc}", file=sys.stderr)
        return 1

    state = "is current" if args.check else "generated"
    print(f"PASS profile index {state} ({index['recordCount']} records)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
