#!/usr/bin/env python3
"""Generate a deterministic, security-conscious repository index."""
import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATEGORIES = ("skills", "agents", "prompts", "project-starters", "templates", "standards", "knowledge", "references", "scripts")
EXCLUDED_DIRS = {".git", ".github", ".idea", ".vscode", "__pycache__", ".pytest_cache", ".mypy_cache", ".tox", "node_modules", "vendor", "dist", "build", "coverage", ".venv", "venv", "env", "generated", "tests"}
EXCLUDED_NAMES = {".env", ".env.local", ".env.production", "secrets.json", "private.json", ".DS_Store"}
EXCLUDED_SUFFIXES = {".pyc", ".pyo", ".tmp", ".temp", ".log", ".cache", ".key", ".pem", ".p12", ".pfx"}


class IndexError(ValueError):
    pass


def category_for(path):
    value = path.as_posix()
    if value.startswith(".agent/skills/"):
        return "skills"
    if value.startswith("templates/project-starters/"):
        return "project-starters"
    for category in CATEGORIES:
        if value.startswith(category + "/"):
            return category
    return None


def is_excluded(path):
    parts = path.parts
    lowered = {part.lower() for part in parts}
    if any(name.lower() in lowered for name in EXCLUDED_DIRS):
        return True
    name = path.name
    return name in EXCLUDED_NAMES or name.startswith(".env.") or name.lower().endswith(tuple(EXCLUDED_SUFFIXES)) or name.endswith("~")


def canonical_bytes(path):
    """Return deterministic bytes for repository indexing across platforms."""
    data = path.read_bytes()

    if b"\x00" in data:
        return data

    try:
        data.decode("utf-8")
    except UnicodeDecodeError:
        return data

    return data.replace(b"\r\n", b"\n")


def build_index(root=ROOT):
    entries = []
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        rel = path.relative_to(root)
        category = category_for(rel)
        if not category or is_excluded(rel):
            continue
        data = canonical_bytes(path)
        entries.append({"path": rel.as_posix(), "category": category, "size": len(data), "sha256": hashlib.sha256(data).hexdigest()})
    entries.sort(key=lambda item: (item["category"], item["path"]))
    counts = {category: sum(item["category"] == category for item in entries) for category in CATEGORIES}
    return {"schemaVersion": "1.0.0", "counts": counts, "files": entries}


def render_json(index):
    return json.dumps(index, indent=2, ensure_ascii=False) + "\n"


def render_markdown(index):
    lines = ["# Generated Repository Map", "", "> Generated from repository source paths. Do not edit this file directly.", ""]
    for category in CATEGORIES:
        lines.extend([f"## {category.replace('-', ' ').title()}", ""])
        paths = [item["path"] for item in index["files"] if item["category"] == category]
        lines.extend(f"- `{path}`" for path in paths)
        if not paths:
            lines.append("- None")
        lines.append("")
    return "\n".join(lines)


def write_or_check(outputs, check=False, root=ROOT):
    stale = []
    for path, content in outputs.items():
        if check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        raise IndexError("stale generated files: " + ", ".join(str(p.relative_to(root)) for p in stale))


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated index files are stale")
    args = parser.parse_args(argv)
    index = build_index(ROOT)
    outputs = {ROOT / "generated/repository-index.json": render_json(index), ROOT / "generated/repository-map.md": render_markdown(index)}
    try:
        write_or_check(outputs, args.check)
    except IndexError as exc:
        print(f"FAIL {exc}", file=sys.stderr)
        return 1
    print(f"PASS repository index {'is current' if args.check else 'generated'} ({len(index['files'])} files)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
